### ISSUE TITLE
Migrating to null safety

### ISSUE THREAD

**Issue by abkorim1998** [onatcipli/social_media_buttons#3]
hello.
could we get a null safety version of it? please

**Comment by nrubin29** [comment]
It seems like the author is AWOL, but I went ahead and did the null safety migration myself in PR #2.

You can use it right now by specifying the dependency in your pubspec like so:

```
social_media_buttons:
  git:
    url: https://github.com/nrubin29/social_media_buttons
    ref: null-safety
```
